name: umbrella_care
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.12.0
  http: ^0.13.6
  intl: ^0.18.1
  hive_flutter: ^1.1.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  table_calendar: ^3.0.9
  khalti_flutter: ^2.2.1
  lottie: ^2.4.0
  dotted_line: ^3.2.2
  firebase_storage: ^11.2.4
  file_picker: ^5.3.1
  easy_pdf_viewer: ^1.0.6
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/UmbrellaCare.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/logos/Schedule.png
    - assets/logos/Report.png
    - assets/logos/chatbot.png
    - assets/logos/Filter.png
    - assets/logos/Doctor.png
    - assets/logos/Record.png
    - assets/logos/hospital.png
    - assets/patientImages/
    - assets/doctorImages/
    - assets/payment/
    - assets/animations/
    - assets/hospital/
    - assets/filterCategories/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
